--
-- PostgreSQL database dump
--

\restrict TKwftoaOcyOyjhlifYUuIaBfe27wHjORt9DmOZAfdVB6jfcG87JHMKfgLBKoKh5

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2026-06-10 14:40:25

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 24979)
-- Name: campanias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campanias (
    id bigint NOT NULL,
    activa boolean,
    descripcion character varying(500),
    fecha_creacion timestamp(6) without time zone,
    fecha_fin timestamp(6) without time zone,
    meta_recaudacion double precision NOT NULL,
    nombre character varying(150) NOT NULL,
    recaudado_actual double precision
);


--
-- TOC entry 217 (class 1259 OID 24978)
-- Name: campanias_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.campanias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campanias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 24987)
-- Name: donaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.donaciones (
    id bigint NOT NULL,
    campania_id bigint,
    donador_id bigint NOT NULL,
    estado character varying(20),
    fecha_donacion timestamp(6) without time zone,
    monto double precision NOT NULL,
    tipo character varying(20) NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 24986)
-- Name: donaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.donaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.donaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24993)
-- Name: donadores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.donadores (
    id bigint NOT NULL,
    email character varying(100) NOT NULL,
    nombre character varying(100) NOT NULL,
    contrasenia character varying(20),
    reset_token character varying(255),
    token_expiry_date timestamp without time zone
);


--
-- TOC entry 221 (class 1259 OID 24992)
-- Name: donadores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.donadores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.donadores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4859 (class 0 OID 24979)
-- Dependencies: 218
-- Data for Name: campanias; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4861 (class 0 OID 24987)
-- Dependencies: 220
-- Data for Name: donaciones; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.donaciones VALUES (1, 1, 4, 'PENDIENTE', '2026-05-13 11:29:11.311338', 100, 'Una vez');
INSERT INTO public.donaciones VALUES (2, 1, 3, 'PENDIENTE', '2026-05-13 12:48:34.244301', 300, 'Una vez');
INSERT INTO public.donaciones VALUES (3, 1, 3, 'PENDIENTE', '2026-05-13 14:21:31.499569', 200, 'Una vez');
INSERT INTO public.donaciones VALUES (4, 1, 5, 'PENDIENTE', '2026-05-14 11:01:41.556733', 100, 'Una vez');
INSERT INTO public.donaciones VALUES (5, 1, 6, 'PENDIENTE', '2026-06-03 22:42:09.757348', 300, 'Una vez');
INSERT INTO public.donaciones VALUES (6, 1, 3, 'PENDIENTE', '2026-06-09 23:18:17.15141', 100, 'Una vez');
INSERT INTO public.donaciones VALUES (7, 1, 8, 'PENDIENTE', '2026-06-10 11:49:16.919324', 200, 'Mensual');
INSERT INTO public.donaciones VALUES (8, 1, 7, 'PENDIENTE', '2026-06-10 14:23:45.333', 300, 'Una vez');


--
-- TOC entry 4863 (class 0 OID 24993)
-- Dependencies: 222
-- Data for Name: donadores; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.donadores VALUES (1, 'juan@mail.com', 'Juan', '123', NULL, NULL);
INSERT INTO public.donadores VALUES (2, 'juan@gmail.com', 'Juan Perez', '123456', NULL, NULL);
INSERT INTO public.donadores VALUES (3, 'Meca123@gmail.com', 'Diego Meca', '12345678', NULL, NULL);
INSERT INTO public.donadores VALUES (4, 'Aren20@gmail.com', 'Aren', '12345A', NULL, NULL);
INSERT INTO public.donadores VALUES (5, 'Marcos2026@gmail.com', 'Marcos Guevara', 'Marcos0102', NULL, NULL);
INSERT INTO public.donadores VALUES (6, 'Luis2026@gmail.com', 'Luis', 'Luis2026', NULL, NULL);
INSERT INTO public.donadores VALUES (8, 'scorpiorojo04@gmail.com', 'Esteban', 'Esteban123', 'b30580c2-81b8-4ea1-b554-2c0bf1753436', '2026-06-10 12:44:12.648015');
INSERT INTO public.donadores VALUES (7, 'aren200501@gmail.com', 'Aren', '1234567890', NULL, NULL);


--
-- TOC entry 4869 (class 0 OID 0)
-- Dependencies: 217
-- Name: campanias_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.campanias_id_seq', 1, false);


--
-- TOC entry 4870 (class 0 OID 0)
-- Dependencies: 219
-- Name: donaciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.donaciones_id_seq', 8, true);


--
-- TOC entry 4871 (class 0 OID 0)
-- Dependencies: 221
-- Name: donadores_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.donadores_id_seq', 8, true);


--
-- TOC entry 4706 (class 2606 OID 24985)
-- Name: campanias campanias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campanias
    ADD CONSTRAINT campanias_pkey PRIMARY KEY (id);


--
-- TOC entry 4708 (class 2606 OID 24991)
-- Name: donaciones donaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.donaciones
    ADD CONSTRAINT donaciones_pkey PRIMARY KEY (id);


--
-- TOC entry 4710 (class 2606 OID 24997)
-- Name: donadores donadores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.donadores
    ADD CONSTRAINT donadores_pkey PRIMARY KEY (id);


--
-- TOC entry 4712 (class 2606 OID 24999)
-- Name: donadores uknqh78btfri7ktwoj2nola0rew; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.donadores
    ADD CONSTRAINT uknqh78btfri7ktwoj2nola0rew UNIQUE (email);


-- Completed on 2026-06-10 14:40:25

--
-- PostgreSQL database dump complete
--

\unrestrict TKwftoaOcyOyjhlifYUuIaBfe27wHjORt9DmOZAfdVB6jfcG87JHMKfgLBKoKh5

